const consolesList = [
    {
        name: 'Playstation 5 GOW Bundle',
        slug: 'Playstation-5-GOW-Bundle',
        category: 'consoles',
        image: '/images/PS5-gow.png',
        price: 650,
        brand: 'Sony',
        rating: 4,
        numReviews: 8,
        countInStock: 20,
        description: 'The PS5 God of War bundle is a special package that combines the highly sought-after PlayStation 5 console with the critically acclaimed game, God of War. This limited edition bundle allows players to dive into the immersive world of God of War on the powerful PS5, experiencing stunning graphics, fast load times, and innovative gameplay features. Join the Spartan warrior Kratos and his son Atreus on an epic journey through Norse mythology, battling mythical creatures, solving puzzles, and uncovering a captivating story. The PS5 God of War bundle offers an incredible gaming experience, combining the next-gen power of the PS5 with the thrilling action and adventure of God of War.',
        isFeatured: true
    },
    {
        name: 'Xbox Series X',
        slug: 'Xbox-Series-X',
        category: 'consoles',
        image: '/images/XBOX-X.png',
        price: 500,
        brand: 'Microsoft',
        rating: 4.7,
        numReviews: 8,
        countInStock: 20,
        description: 'The Xbox Series X is a powerful gaming console designed by Microsoft. It offers a cutting-edge gaming experience with its advanced hardware and features. The console boasts high-performance capabilities, including support for 4K resolution, ray tracing technology, and fast load times thanks to its custom SSD. The Xbox Series X also features backward compatibility, allowing you to play a wide range of games from previous Xbox generations. With its sleek design and innovative features like Quick Resume, Smart Delivery, and Xbox Game Pass, the Xbox Series X delivers a premium gaming experience for both casual and hardcore gamers alike.',
        isFeatured: true
    },
    {
        name: 'Xbox Series S',
        slug: 'Xbox-Series-S',
        category: 'consoles',
        image: '/images/XBOX-S.png',
        price: 400,
        brand: 'Microsoft',
        rating: 4.3,
        numReviews: 2,
        countInStock: 20,
        description: "The Xbox Series S is an incredibly compact gaming console, designed to be the smallest Xbox ever released. Despite its small size, it doesn't compromise on performance, offering impressive hardware capabilities and a high-speed SSD for quick load times. With support for up to 1440p resolution and fast frame rates, it delivers a visually immersive gaming experience. The Series S supports ray tracing for enhanced graphics and provides access to a vast library of games, including Xbox Game Pass. Its compact form factor makes it perfect for those with limited space or who prefer a portable gaming setup. The Xbox Series S is a powerhouse in a small package, delivering big on gaming performance.",
    },
    {
        name: 'Nintendo Switch Mario Bundle',
        slug: 'Nintendo-Switch-Mario-Bundle',
        category: 'consoles',
        image: '/images/switch.png',
        price: 300,
        brand: 'Nintendo',
        rating: 4.3,
        numReviews: 2,
        countInStock: 20,
        description: "The Nintendo Switch Mario Bundle is a special edition package that includes a Nintendo Switch console with a Mario-themed design and pre-installed Mario games. It's a limited-edition bundle that celebrates the iconic plumber's adventures, featuring a vibrant red and blue console with artwork of Mario characters. With the included games like 'Super Mario Odyssey' and 'Mario Kart 8 Deluxe', fans can enjoy Mario's exciting platforming and racing adventures right out of the box. It's the perfect bundle for Mario enthusiasts and Nintendo fans looking for a unique and immersive gaming experience.",
        isFeatured: true
    },
    {
        name: 'Playstation 5 Digital Edition',
        slug: 'Playstation-5-Digital-Edition',
        category: 'consoles',
        image: '/images/PS5-digital.png',
        price: 600,
        brand: 'Sony',
        rating: 4.3,
        numReviews: 2,
        countInStock: 20,
        description: "The PlayStation 5 Digital Edition is a disc-less version of the PlayStation 5 console. It offers the same powerful hardware and features as the standard version but focuses solely on digital game downloads. With no disc drive, all games must be purchased and downloaded from the PlayStation Store. It's a sleek and streamlined option for gamers who prefer a purely digital gaming experience.",
    },
]

export default consolesList;