import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            firstName: 'Apparently',
            lastName: 'Pyro',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true,
        },
        {
            firstName: 'John',
            lastName: 'Smith',
            email: 'user@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: false,
        },
    ],
    products: [
        {
            name: 'Playstation 5 GOW Bundle',
            slug: 'Playstation-5-GOW-Bundle',
            category: 'consoles',
            image: '/images/PS5-gow.png',
            price: 650,
            brand: 'Sony',
            rating: 4,
            numReviews: 8,
            countInStock: 20,
            description: 'The PS5 God of War bundle is a special package that combines the highly sought-after PlayStation 5 console with the critically acclaimed game, God of War. This limited edition bundle allows players to dive into the immersive world of God of War on the powerful PS5, experiencing stunning graphics, fast load times, and innovative gameplay features. Join the Spartan warrior Kratos and his son Atreus on an epic journey through Norse mythology, battling mythical creatures, solving puzzles, and uncovering a captivating story. The PS5 God of War bundle offers an incredible gaming experience, combining the next-gen power of the PS5 with the thrilling action and adventure of God of War.',
            isFeatured: true
        },
        {
            name: 'Xbox Series X',
            slug: 'Xbox-Series-X',
            category: 'consoles',
            image: '/images/XBOX-X.png',
            price: 500,
            brand: 'Microsoft',
            rating: 4.7,
            numReviews: 8,
            countInStock: 20,
            description: 'The Xbox Series X is a powerful gaming console designed by Microsoft. It offers a cutting-edge gaming experience with its advanced hardware and features. The console boasts high-performance capabilities, including support for 4K resolution, ray tracing technology, and fast load times thanks to its custom SSD. The Xbox Series X also features backward compatibility, allowing you to play a wide range of games from previous Xbox generations. With its sleek design and innovative features like Quick Resume, Smart Delivery, and Xbox Game Pass, the Xbox Series X delivers a premium gaming experience for both casual and hardcore gamers alike.',
            isFeatured: true
        },
        {
            name: 'Xbox Series S',
            slug: 'Xbox-Series-S',
            category: 'consoles',
            image: '/images/XBOX-S.png',
            price: 400,
            brand: 'Microsoft',
            rating: 4.3,
            numReviews: 2,
            countInStock: 20,
            description: "The Xbox Series S is an incredibly compact gaming console, designed to be the smallest Xbox ever released. Despite its small size, it doesn't compromise on performance, offering impressive hardware capabilities and a high-speed SSD for quick load times. With support for up to 1440p resolution and fast frame rates, it delivers a visually immersive gaming experience. The Series S supports ray tracing for enhanced graphics and provides access to a vast library of games, including Xbox Game Pass. Its compact form factor makes it perfect for those with limited space or who prefer a portable gaming setup. The Xbox Series S is a powerhouse in a small package, delivering big on gaming performance.",
            isFeatured: true
        },
        {
            name: 'Nintendo Switch Mario Bundle',
            slug: 'Nintendo-Switch-Mario-Bundle',
            category: 'consoles',
            image: '/images/switch.png',
            price: 300,
            brand: 'Nintendo',
            rating: 4.3,
            numReviews: 2,
            countInStock: 20,
            description: "The Nintendo Switch Mario Bundle is a special edition package that includes a Nintendo Switch console with a Mario-themed design and pre-installed Mario games. It's a limited-edition bundle that celebrates the iconic plumber's adventures, featuring a vibrant red and blue console with artwork of Mario characters. With the included games like 'Super Mario Odyssey' and 'Mario Kart 8 Deluxe', fans can enjoy Mario's exciting platforming and racing adventures right out of the box. It's the perfect bundle for Mario enthusiasts and Nintendo fans looking for a unique and immersive gaming experience.",
            isFeatured: true
        },
        {
            name: 'Playstation 5 Digital Edition',
            slug: 'Playstation-5-Digital-Edition',
            category: 'consoles',
            image: '/images/PS5-digital.png',
            price: 600,
            brand: 'Sony',
            rating: 4.3,
            numReviews: 2,
            countInStock: 20,
            description: "The PlayStation 5 Digital Edition is a disc-less version of the PlayStation 5 console. It offers the same powerful hardware and features as the standard version but focuses solely on digital game downloads. With no disc drive, all games must be purchased and downloaded from the PlayStation Store. It's a sleek and streamlined option for gamers who prefer a purely digital gaming experience.",
        },
        {
            name: 'CyberPowerPC Gamer Xtreme Vr',
            slug: 'CyberPowerPC-Gamer-Xtreme-Vr',
            category: 'desktops',
            image: '/images/desktop1.png',
            price: 1200,
            brand: 'CyberPowerPC',
            rating: 4.3,
            numReviews: 12,
            countInStock: 20,
            description: "The CyberPowerPC Gamer Xtreme VR is a gaming PC designed to provide an immersive virtual reality experience. Equipped with powerful components, including a high-performance processor and a dedicated graphics card, it delivers smooth and lag-free gameplay, perfect for VR gaming. The sleek and modern design of the CyberPowerPC Gamer Xtreme VR adds a touch of style to any gaming setup, while its advanced cooling system ensures optimal performance during intense gaming sessions. With its ample storage space and customizable RGB lighting, the Gamer Xtreme VR offers both power and aesthetics. Whether you're a VR enthusiast or a hardcore gamer, the CyberPowerPC Gamer Xtreme VR is built to deliver a seamless and captivating gaming experience.",
        },
        {
            name: 'Dell Alienware Aurora R13',
            slug: 'Dell-Alienware-Aurora-R13',
            category: 'desktops',
            image: '/images/desktop2.png',
            price: 1200,
            brand: 'Dell',
            rating: 4.2,
            numReviews: 2,
            countInStock: 20,
            description: "The Dell Alienware Aurora R13 is a gaming powerhouse that combines cutting-edge performance with stunning design. Equipped with high-performance components, including a powerful processor and advanced graphics card, it delivers smooth and immersive gaming experiences with exceptional graphics and speed. The sleek and futuristic design of the Dell Alienware Aurora R13 adds a touch of sophistication to any gaming setup, while its innovative cooling system ensures optimal performance during intense gaming sessions. With customizable RGB lighting and a range of connectivity options, the Dell Alienware Aurora R13 offers a fully immersive gaming experience. Whether you're a competitive gamer or a multimedia enthusiast, the Dell Alienware Aurora R13 is built to deliver unmatched performance and take your gaming adventures to new heights.",
        },
        {
            name: 'MSI Aegis RS',
            slug: 'MSI-Aegis-RS',
            category: 'desktops',
            image: '/images/desktop3.png',
            price: 3000,
            brand: 'MSI',
            rating: 5.0,
            numReviews: 5,
            countInStock: 20,
            description: "The MSI Aegis RS is a powerhouse gaming PC that delivers exceptional performance and cutting-edge features. Equipped with high-performance hardware, including a top-tier processor and advanced graphics card, it provides seamless gaming experiences with stunning visuals and smooth gameplay. The sleek and futuristic design of the MSI Aegis RS adds a touch of style to any gaming setup, while its robust cooling system ensures efficient heat dissipation for optimal performance even during intense gaming sessions. With customizable RGB lighting and ample connectivity options, the MSI Aegis RS offers a complete and immersive gaming experience. Whether you're a hardcore gamer or a content creator, the MSI Aegis RS is built to deliver uncompromising performance and elevate your gaming adventures to new heights.",
        },
        {
            name: 'MSI Infinite RS 13th',
            slug: 'MSI-Infinite-RS-13th',
            category: 'desktops',
            image: '/images/desktop4.png',
            price: 4200,
            brand: 'MSI',
            rating: 5.0,
            numReviews: 1,
            countInStock: 20,
            description: "The MSI Infinite RS 13th is a powerful gaming PC that offers impressive performance and reliability. With its high-performance components, including a powerful processor and advanced graphics card, it delivers smooth and immersive gaming experiences. The sleek and futuristic design of the MSI Infinite RS 13th adds a touch of style to any gaming setup, while its optimized airflow and cooling system ensure efficient heat dissipation for prolonged gaming sessions. Whether you're a competitive gamer or a multimedia enthusiast, the MSI Infinite RS 13th provides a reliable and high-performance gaming solution that can handle demanding tasks with ease.",
            isFeatured: true
        },
        {
            name: 'Overclockers Germanium',
            slug: 'Overclockers-Germanium',
            category: 'desktops',
            image: '/images/desktop5.png',
            price: 2800,
            brand: 'Overclockers',
            rating: 5.0,
            numReviews: 7,
            countInStock: 20,
            description: "The Overclockers Germanium is a high-performance gaming PC that is designed to deliver exceptional power and speed. Equipped with top-of-the-line hardware, including a high-end processor and advanced graphics card, it delivers smooth and immersive gaming experiences. The sleek and stylish design of the Overclockers Germanium adds a touch of sophistication to any gaming setup, while its advanced cooling system ensures efficient heat dissipation for optimal performance. Whether you're a hardcore gamer or a professional content creator, the Overclockers Germanium is built to handle demanding tasks with ease, making it a top choice for those seeking uncompromising performance and reliability.",
        },
        {
            name: 'NZXT Player Three Prime',
            slug: 'NZXT-Player-Three-Prime',
            category: 'desktops',
            image: '/images/desktop6.png',
            price: 3800,
            brand: 'NZXT',
            rating: 5.0,
            numReviews: 1,
            countInStock: 20,
            description: "The NZXT Player Three Prime is a compact gaming PC that offers impressive performance in a small form factor. Powered by a robust processor and a capable graphics card, it delivers smooth and responsive gaming experiences. Despite its compact size, the NZXT Player Three Prime doesn't compromise on style, featuring a sleek and modern design that will enhance any gaming setup. It also offers excellent thermal management, ensuring optimal cooling and preventing overheating during intense gaming sessions. Whether you're a casual gamer or a competitive enthusiast, the NZXT Player Three Prime provides a reliable and powerful gaming solution that is perfect for smaller spaces.",
        },
        {
            name: 'Corsair One i300',
            slug: 'Corsair-One-i300',
            category: 'desktops',
            image: '/images/desktop7.png',
            price: 4500,
            brand: 'Corsair',
            rating: 5.0,
            numReviews: 4,
            countInStock: 20,
            description: "The Corsair One i300 is a compact and formidable gaming PC that packs a punch. Designed with high-performance components, including a powerful processor and top-tier graphics card, it delivers exceptional gaming performance without compromising on space or style. The sleek and compact design of the Corsair One i300 makes it perfect for small gaming setups or tight spaces, while its advanced cooling system ensures optimal performance during intense gaming sessions. With its powerful hardware and attention to detail, the Corsair One i300 is an excellent choice for gamers who demand both power and aesthetics in their gaming rig.",
        },
        {
            name: 'CyberPowerPC Gamer Master',
            slug: 'CyberPowerPC-Gamer-Master',
            category: 'desktops',
            image: '/images/desktop8.png',
            price: 900,
            brand: 'CyberPowerPC',
            rating: 4.3,
            numReviews: 12,
            countInStock: 20,
            description: "The CyberPowerPC Gamer Master is a high-performance gaming PC designed for immersive gaming experiences. Equipped with powerful hardware, including a robust processor and advanced graphics card, it effortlessly handles demanding games with ease. The sleek design and customizable RGB lighting add a touch of style to any gaming setup. Whether you're a casual gamer or a dedicated enthusiast, the CyberPowerPC Gamer Master is built to deliver exceptional gaming performance and take your gameplay to the next level.",
        },
        {
            name: 'CyberPowerPC Gamer Supreme',
            slug: 'CyberPowerPC-Gamer-Supreme',
            category: 'desktops',
            image: '/images/desktop9.png',
            price: 1800,
            brand: 'CyberPowerPC',
            rating: 5.0,
            numReviews: 8,
            countInStock: 20,
            description: "The CyberPowerPC Gamer Supreme is a top-of-the-line gaming PC that pushes the boundaries of performance. With its powerful hardware configuration, including a high-end processor and cutting-edge graphics card, it delivers unrivaled speed and graphics capabilities for an immersive gaming experience. The sleek and modern design of the Gamer Supreme, combined with customizable RGB lighting, adds a touch of sophistication to any gaming setup. Whether you're a competitive gamer or a content creator, the CyberPowerPC Gamer Supreme is built to handle the most demanding games and applications, making it the ultimate choice for enthusiasts seeking top-tier performance.",
        },
        {
            name: 'Gigabyte Aorus 17',
            slug: 'Gigabyte-Aorus-17',
            category: 'laptops',
            image: '/images/laptop1.png',
            price: 2500,
            brand: 'Gigabyte',
            rating: 5.0,
            numReviews: 17,
            countInStock: 20,
            description: "The Gigabyte Aorus 17 gaming laptop is a powerful and feature-packed device designed to deliver an exceptional gaming experience. With its high-performance hardware, including top-tier processors and graphics cards, it ensures smooth gameplay and stunning visuals. The laptop boasts a large, high-resolution display, offering immersive gaming and vibrant colors. Its advanced cooling system helps to keep temperatures under control during intense gaming sessions. Additionally, the Aorus 17 is equipped with a range of customizable RGB lighting options, enhancing its aesthetic appeal. Overall, the Aorus 17 is a top choice for gamers seeking top-notch performance and immersive gaming experience on a portable platform.",
        },
        {
            name: 'Gigabyte G5',
            slug: 'Gigabyte-G5',
            category: 'laptops',
            image: '/images/laptop2.png',
            price: 900,
            brand: 'Gigabyte',
            rating: 4.7,
            numReviews: 14,
            countInStock: 20,
            description: "The Gigabyte G5 is a gaming laptop that packs a punch in terms of performance. With its powerful hardware and dedicated graphics card, it delivers smooth gaming and impressive visuals. The laptop features a vibrant display, providing an immersive gaming experience. It also boasts an efficient cooling system to maintain optimal temperatures during extended gaming sessions. With its sleek design and customizable features, the Gigabyte G5 offers both style and substance for gamers looking for an enjoyable gaming experience.",
            isFeatured: true
        },
        {
            name: 'Lenovo Legion Pro 7i',
            slug: 'Lenovo-Legion-Pro-7i',
            category: 'laptops',
            image: '/images/laptop3.png',
            price: 2000,
            brand: 'Lenovo',
            rating: 5.0,
            numReviews: 8,
            countInStock: 20,
            description: "The Lenovo Legion Pro 7i is a high-performance gaming laptop designed to deliver an exceptional gaming experience. With its powerful hardware, including top-tier processors and graphics cards, it ensures smooth gameplay and impressive visuals. The laptop features a vibrant and immersive display, offering stunning visuals for gaming and multimedia. Its advanced cooling system helps to prevent overheating during intense gaming sessions. With its sleek design and customizable RGB lighting, the Legion Pro 7i is a stylish choice for gamers seeking top-notch performance and immersive gameplay.",
        },
        {
            name: 'MSI Raider GE76',
            slug: 'MSI-Raider-GE76',
            category: 'laptops',
            image: '/images/laptop4.png',
            price: 4000,
            brand: 'MSI',
            rating: 5.0,
            numReviews: 2,
            countInStock: 20,
            description: "The MSI Raider GE76 is a powerful gaming laptop that delivers exceptional performance. With its high-performance hardware and top-tier graphics card, it provides smooth gameplay and impressive visuals. The laptop features a large, high-resolution display, offering an immersive gaming experience. Its advanced cooling system helps maintain optimal temperatures during intense gaming sessions. With its sleek design and customizable RGB lighting, the Raider GE76 combines power and style for gamers seeking an immersive gaming experience on the go.",
        },
        {
            name: 'Razer Blade 15',
            slug: 'Razer-Blade-15',
            category: 'laptops',
            image: '/images/laptop5.png',
            price: 2800,
            brand: 'Razer',
            rating: 5.0,
            numReviews: 6,
            countInStock: 20,
            description: "The Razer Blade 15 is a premium gaming laptop that combines power and portability. With its high-performance hardware and dedicated graphics card, it delivers smooth gameplay and stunning visuals. The laptop features a sleek design and a thin bezel display, providing an immersive gaming experience. Its advanced cooling system ensures efficient heat dissipation during intense gaming sessions. The Razer Blade 15 is a stylish choice for gamers seeking top-tier performance in a compact and visually appealing package.",
        },
        {
            name: 'Razer Blade 18',
            slug: 'Razer-Blade-18',
            category: 'laptops',
            image: '/images/laptop6.png',
            price: 3000,
            brand: 'Razer',
            rating: 5.0,
            numReviews: 10,
            countInStock: 20,
            description: "The Razer Blade 18 is an impressive gaming laptop with high-performance capabilities. It boasts a sleek design and a large high-resolution display, offering stunning visuals. The laptop incorporates advanced cooling technology to ensure optimal performance during intense gaming sessions. With customizable RGB lighting, the Razer Blade 18 adds a touch of personalization to the gaming experience. Overall, it is a top choice for gamers looking for power, style, and immersive gameplay in a portable package.",
        },
        {
            name: 'Asus ROG Strix Scar 17',
            slug: 'Asus-ROG-Strix-Scar-17',
            category: 'laptops',
            image: '/images/laptop7.png',
            price: 2800,
            brand: 'Asus',
            rating: 4.3,
            numReviews: 17,
            countInStock: 20,
            description: "The Asus ROG Strix Scar 17 is a high-performance gaming laptop designed to elevate your gaming experience. With its powerful hardware and dedicated graphics card, it delivers smooth gameplay and exceptional visuals. The laptop features a large, high-refresh-rate display, offering immersive and fluid gaming visuals. Its advanced cooling system ensures efficient heat dissipation, allowing for prolonged gaming sessions without overheating. With its bold design and customizable RGB lighting, the ROG Strix Scar 17 stands out as a stylish choice for gamers seeking top-tier performance and an immersive gaming experience.",
        },
        {
            name: 'Asus ROG Zephyrus G14',
            slug: 'Asus-ROG-Zephyrus-G14',
            category: 'laptops',
            image: '/images/laptop8.png',
            price: 1800,
            brand: 'Asus',
            rating: 4.7,
            numReviews: 23,
            countInStock: 20,
            description: "The Asus ROG Zephyrus G14 is a compact and powerful gaming laptop that redefines portable gaming. With its high-performance hardware and dedicated graphics card, it delivers smooth gameplay and impressive visuals. The laptop features a stunning 14-inch display with a high refresh rate, offering immersive and vibrant gaming experiences. Its innovative cooling system ensures optimal performance during intense gaming sessions. With its sleek and lightweight design, the Zephyrus G14 is a perfect choice for gamers on the go, combining portability and power for an unmatched gaming experience.",
        },
        {
            name: 'Asus ROG Zephyrus M16',
            slug: 'Asus-ROG-Zephyrus-M16',
            category: 'laptops',
            image: '/images/laptop9.png',
            price: 2500,
            brand: 'Asus',
            rating: 4.8,
            numReviews: 9,
            countInStock: 20,
            description: "The Asus ROG Zephyrus M16 is a cutting-edge gaming laptop that offers an exceptional gaming experience. With its powerful hardware and dedicated graphics card, it delivers smooth gameplay and stunning visuals. The laptop features a vibrant and immersive display with a high refresh rate, providing fluid and lifelike visuals. Its advanced cooling system ensures optimal performance even during intense gaming sessions. With its sleek and slim design, the Zephyrus M16 is a stylish and portable choice for gamers who prioritize both power and aesthetics.",
        },

        {
            name: 'asus strix',
            slug: 'asus-strix',
            category: 'Laptops',
            image: '/images/laptop1.png',
            price: 123,
            brand: 'Asus',
            rating: 7.4,
            numReviews: 14,
            countInStock: 20,
            description: 'The ASUS ROG Strix SCAR 17 (2023) G733 is a top-of-the-line gaming laptop that offers exceptional performance and impressive visuals. It is designed for demanding gamers who want the best experience and for work that requires a powerful processor and wild graphics card NVIDIA RTX 4080 graphics card 17.3 WQHD display with a 240 Hz refresh rate Full-sized RGB backlit keyboard Aura Sync Light Bar Wi-Fi 6E and Bluetooth 5.2  '

        },

        {
            name: 'RAZER blade 15',
            slug: 'RAZER-blade-15',
            category: 'laptops',
            image: '/images/laptop2.png',
            price: 750,
            brand: 'Razer',
            rating: 9.4,
            numReviews: 14,
            countInStock: 20,
            description: "The Razer Blade 15 is a sleek and powerful gaming laptop known for its premium design, high-performance hardware, and vibrant display. It features a thin and lightweight aluminum chassis, a 15.6-inch display (available in various resolutions), powerful Intel Core processors, dedicated NVIDIA graphics cards, ample storage options, and a range of connectivity ports. With its advanced cooling system and stylish design, the Razer Blade 15 offers an excellent gaming experience for enthusiasts on the go. ",

        },
        {
            name: 'The MSI GL66 Pulse',
            slug: 'The-MSI-GL66-Pulse',
            category: 'laptops',
            image: '/images/laptop3.png',
            price: 500,
            brand: 'MSI',
            rating: 8.4,
            numReviews: 14,
            countInStock: 20,
            description: "The MSI GL66 Pulse is a gaming laptop designed for gamers seeking a blend of performance, affordability, and stylish design. With its modern and aggressive design, sturdy build quality, and gaming-centric features, this laptop offers an immersive gaming experience. It typically features a 15-inch display, powerful hardware components, and customizable keyboard lighting. The GL66 Pulse is a reliable option for gamers looking for a balance between performance and value. ",

        },
        {
            name: 'GIGABYTE AORUS',
            slug: 'GIGABYTE-AORUS',
            category: 'laptops',
            image: '/images/laptop4.png',
            price: 850,
            brand: 'Gigabyte',
            rating: 4.4,
            numReviews: 14,
            countInStock: 20,
            description: "GIGABYTE AORUS is a brand specializing in high-performance gaming hardware, including gaming laptops, motherboards, graphics cards, monitors, and peripherals. With a focus on delivering top-notch performance, advanced features, and stylish designs, GIGABYTE AORUS products are designed for gamers and enthusiasts who demand the best in gaming technology. From powerful gaming laptops to robust motherboards, cutting-edge graphics cards, immersive monitors, and precision-engineered peripherals, GIGABYTE AORUS offers a comprehensive range of products to enhance the gaming experience. ",

        },
        {
            name: 'HP Pavilion Gaming',
            slug: 'HP-Pavilion-Gaming',
            category: 'laptops',
            image: '/images/laptop5.png',
            price: 900,
            brand: 'Hp',
            rating: 5.4,
            numReviews: 16,
            countInStock: 20,
            description: "HP Pavilion Gaming is an affordable lineup of gaming laptops and desktops designed for budget-conscious gamers. These devices offer reliable performance and gaming features without breaking the bank. With options for both laptops and desktops, HP Pavilion Gaming provides a balance of affordability and functionality. The devices feature stylish designs, gaming-centric features such as high refresh rate displays and customizable RGB lighting, and a range of hardware configurations to suit different gaming needs. If you're looking for an entry-level gaming solution that delivers value for money, HP Pavilion Gaming is worth considering.",

        },
        {
            name: 'HP Victus',
            slug: 'HP-Victus',
            category: 'laptops',
            image: '/images/laptop6.png',
            price: 365,
            brand: 'Hp',
            rating: 6.4,
            numReviews: 16,
            countInStock: 20,
            description: "HP Victus is a gaming laptop series by HP that combines performance, affordability, and a stylish design. Designed for budget-conscious gamers, HP Victus laptops offer a balance of gaming capabilities and value. They typically feature powerful processors, dedicated graphics cards, high refresh rate displays, and customizable RGB lighting. With a focus on delivering a reliable gaming experience, HP Victus laptops are suitable for casual to mid-level gaming. The series offers a range of options to choose from, providing gamers with the flexibility to find a configuration that suits their needs and budget.",

        },
        {
            name: 'ACER Predator',
            slug: 'ACER-Predator',
            category: 'laptops',
            image: '/images/laptop7.png',
            price: 4700,
            brand: 'ACER',
            rating: 6.4,
            numReviews: 16,
            countInStock: 20,
            description: "The ACER Predator Helios 300 is a sleek and powerful gaming laptop known for its high-performance hardware, including Intel Core processors and NVIDIA GeForce graphics cards. With its aggressive design, advanced cooling system, and vibrant display options, the Predator Helios 300 offers an immersive gaming experience at a competitive price point.",

        },
        {
            name: 'SteelSeries Arctis Pro',
            slug: 'SteelSeries-Arctis-Pro',
            category: 'peripherals',
            image: '/images/peri1.png',
            price: 310,
            brand: 'SteelSeries',
            rating: 6.4,
            numReviews: 16,
            countInStock: 20,
            description: "The SteelSeries Arctis Pro is a premium gaming headset designed to deliver exceptional audio quality and comfort. With high-resolution speaker drivers and DTS Headphone:X v2.0 surround sound technology, it immerses you in a rich and precise gaming audio experience."
        },
        {
            name: 'SteelSeries Arctis 7',
            slug: 'SteelSeries-Arctis-7',
            category: 'peripherals',
            image: '/images/peri2.png',
            price: 210,
            brand: 'SteelSeries',
            rating: 6.4,
            numReviews: 16,
            countInStock: 20,
            description: "The SteelSeries Arctis 7+ is a wireless gaming headset that combines high-performance audio and convenience. It offers lag-free wireless connectivity using a 2.4GHz wireless dongle, providing a reliable connection and allowing you to move freely while gaming. With its premium speaker drivers and DTS Headphone:X v2.0 surround sound technology."
        },
        {
            name: 'Sony DualSense',
            slug: 'Sony-DualSense',
            category: 'peripherals',
            image: '/images/peri3.png',
            price: 350,
            brand: 'Sony',
            rating: 6.4,
            numReviews: 16,
            countInStock: 20,
            description: "The Sony DualSense controller is a next-generation gaming controller designed for the PlayStation 5 console. It features an innovative design and advanced technology to enhance your gaming experience."
        },
        {
            name: 'Razer Kraken V3 X',
            slug: 'Razer-Kraken-V3-X',
            category: 'peripherals',
            image: '/images/peri4.png',
            price: 890,
            brand: 'Razer  ',
            rating: 6.4,
            numReviews: 16,
            countInStock: 20,
            description: "The Razer Kraken V3 X is a lightweight gaming headset that delivers immersive audio and comfort for gamers. With custom-tuned 40mm drivers, it provides clear and powerful sound, enhancing your gaming experience"
        },
        {
            name: 'Xbox Wireless Controller Carbon Black Xbs',
            slug: 'Xbox-Wireless-Controller-Carbon-Black-Xbs',
            category: 'peripherals',
            image: '/images/peri5.png',
            price: 80,
            brand: 'Microsoft',
            rating: 6.4,
            numReviews: 16,
            countInStock: 20,
            description: " is a versatile and ergonomic gamepad designed for Xbox consoles and compatible Windows PCs. It offers a seamless and responsive wireless connection, allowing you to enjoy gaming without the constraints of cables. "
        },
        {
            name: 'Razer Viper',
            slug: 'Razer-Viper',
            category: 'peripherals',
            image: '/images/peri6.png',
            price: 530,
            brand: 'Razer  ',
            rating: 6.4,
            numReviews: 16,
            countInStock: 20,
            description: "The Razer Viper is a high-performance gaming mouse designed for competitive gamers. It boasts a lightweight and ambidextrous design, making it suitable for both left and right-handed users"
        },

        {
            name: 'Razer Basilisk V3',
            slug: 'Razer-Basilisk-V3',
            category: 'peripherals',
            image: '/images/peri7.png',
            price: 70,
            brand: 'Razer  ',
            rating: 6.4,
            numReviews: 16,
            countInStock: 20,
            description: "The Razer Basilisk V3 is a feature-rich gaming mouse designed for precision and customization. It features Razer's Focus+ 26,000 DPI optical sensor, providing exceptional tracking accuracy and sensitivity for precise movements. The Basilisk V3 incorporates 11 programmable buttons"
        },
        {
            name: 'Logitech G915',
            slug: 'Logitech-G915',
            category: 'peripherals',
            image: '/images/peri8.png',
            price: 50,
            brand: 'Logitech  ',
            rating: 7.4,
            numReviews: 16,
            countInStock: 20,
            description: "The Logitech G915 is a premium wireless gaming keyboard that combines sleek design with advanced features. It features Logitech's low-profile GL mechanical switches, which offer a fast and precise typing experience with reduced key travel distance. "
        },
        {
            name: 'Sony PULSE 3D',
            slug: 'Sony-PULSE-3D',
            category: 'peripherals',
            image: '/images/peri9.png',
            price: 50,
            brand: 'Sony',
            rating: 7.4,
            numReviews: 16,
            countInStock: 20,
            description: "The Sony PULSE 3D is a wireless gaming headset specifically designed for the PlayStation 5 console. It provides a high-quality audio experience and features Tempest 3D AudioTech, which delivers immersive and spatial sound.  "
        },
    ],
};




export default data;


