const desktopsList = [
    {
        name: 'CyberPowerPC Gamer Xtreme Vr',
        slug: 'CyberPowerPC-Gamer-Xtreme-Vr',
        category: 'desktops',
        image: '/images/desktop1.png',
        price: 1200,
        brand: 'CyberPowerPC',
        rating: 4.3,
        numReviews: 12,
        countInStock: 20,
        description: "The CyberPowerPC Gamer Xtreme VR is a gaming PC designed to provide an immersive virtual reality experience. Equipped with powerful components, including a high-performance processor and a dedicated graphics card, it delivers smooth and lag-free gameplay, perfect for VR gaming. The sleek and modern design of the CyberPowerPC Gamer Xtreme VR adds a touch of style to any gaming setup, while its advanced cooling system ensures optimal performance during intense gaming sessions. With its ample storage space and customizable RGB lighting, the Gamer Xtreme VR offers both power and aesthetics. Whether you're a VR enthusiast or a hardcore gamer, the CyberPowerPC Gamer Xtreme VR is built to deliver a seamless and captivating gaming experience.",
    },
    {
        name: 'Dell Alienware Aurora R13',
        slug: 'Dell-Alienware-Aurora-R13',
        category: 'desktops',
        image: '/images/desktop2.png',
        price: 1200,
        brand: 'Dell',
        rating: 4.2,
        numReviews: 2,
        countInStock: 20,
        description: "The Dell Alienware Aurora R13 is a gaming powerhouse that combines cutting-edge performance with stunning design. Equipped with high-performance components, including a powerful processor and advanced graphics card, it delivers smooth and immersive gaming experiences with exceptional graphics and speed. The sleek and futuristic design of the Dell Alienware Aurora R13 adds a touch of sophistication to any gaming setup, while its innovative cooling system ensures optimal performance during intense gaming sessions. With customizable RGB lighting and a range of connectivity options, the Dell Alienware Aurora R13 offers a fully immersive gaming experience. Whether you're a competitive gamer or a multimedia enthusiast, the Dell Alienware Aurora R13 is built to deliver unmatched performance and take your gaming adventures to new heights.",
    },
    {
        name: 'MSI Aegis RS',
        slug: 'MSI-Aegis-RS',
        category: 'desktops',
        image: '/images/desktop3.png',
        price: 3000,
        brand: 'MSI',
        rating: 5.0,
        numReviews: 5,
        countInStock: 20,
        description: "The MSI Aegis RS is a powerhouse gaming PC that delivers exceptional performance and cutting-edge features. Equipped with high-performance hardware, including a top-tier processor and advanced graphics card, it provides seamless gaming experiences with stunning visuals and smooth gameplay. The sleek and futuristic design of the MSI Aegis RS adds a touch of style to any gaming setup, while its robust cooling system ensures efficient heat dissipation for optimal performance even during intense gaming sessions. With customizable RGB lighting and ample connectivity options, the MSI Aegis RS offers a complete and immersive gaming experience. Whether you're a hardcore gamer or a content creator, the MSI Aegis RS is built to deliver uncompromising performance and elevate your gaming adventures to new heights.",
    },
    {
        name: 'MSI Infinite RS 13th',
        slug: 'MSI-Infinite-RS-13th',
        category: 'desktops',
        image: '/images/desktop4.png',
        price: 4200,
        brand: 'MSI',
        rating: 5.0,
        numReviews: 1,
        countInStock: 20,
        description: "The MSI Infinite RS 13th is a powerful gaming PC that offers impressive performance and reliability. With its high-performance components, including a powerful processor and advanced graphics card, it delivers smooth and immersive gaming experiences. The sleek and futuristic design of the MSI Infinite RS 13th adds a touch of style to any gaming setup, while its optimized airflow and cooling system ensure efficient heat dissipation for prolonged gaming sessions. Whether you're a competitive gamer or a multimedia enthusiast, the MSI Infinite RS 13th provides a reliable and high-performance gaming solution that can handle demanding tasks with ease.",
    },
    {
        name: 'Overclockers Germanium',
        slug: 'Overclockers-Germanium',
        category: 'desktops',
        image: '/images/desktop5.png',
        price: 2800,
        brand: 'Overclockers',
        rating: 5.0,
        numReviews: 7,
        countInStock: 20,
        description: "The Overclockers Germanium is a high-performance gaming PC that is designed to deliver exceptional power and speed. Equipped with top-of-the-line hardware, including a high-end processor and advanced graphics card, it delivers smooth and immersive gaming experiences. The sleek and stylish design of the Overclockers Germanium adds a touch of sophistication to any gaming setup, while its advanced cooling system ensures efficient heat dissipation for optimal performance. Whether you're a hardcore gamer or a professional content creator, the Overclockers Germanium is built to handle demanding tasks with ease, making it a top choice for those seeking uncompromising performance and reliability.",
    },
    {
        name: 'NZXT Player Three Prime',
        slug: 'NZXT-Player-Three-Prime',
        category: 'desktops',
        image: '/images/desktop6.png',
        price: 3800,
        brand: 'NZXT',
        rating: 5.0,
        numReviews: 1,
        countInStock: 20,
        description: "The NZXT Player Three Prime is a compact gaming PC that offers impressive performance in a small form factor. Powered by a robust processor and a capable graphics card, it delivers smooth and responsive gaming experiences. Despite its compact size, the NZXT Player Three Prime doesn't compromise on style, featuring a sleek and modern design that will enhance any gaming setup. It also offers excellent thermal management, ensuring optimal cooling and preventing overheating during intense gaming sessions. Whether you're a casual gamer or a competitive enthusiast, the NZXT Player Three Prime provides a reliable and powerful gaming solution that is perfect for smaller spaces.",
    },
    {
        name: 'Corsair One i300',
        slug: 'Corsair-One-i300',
        category: 'desktops',
        image: '/images/desktop7.png',
        price: 4500,
        brand: 'Corsair',
        rating: 5.0,
        numReviews: 4,
        countInStock: 20,
        description: "The Corsair One i300 is a compact and formidable gaming PC that packs a punch. Designed with high-performance components, including a powerful processor and top-tier graphics card, it delivers exceptional gaming performance without compromising on space or style. The sleek and compact design of the Corsair One i300 makes it perfect for small gaming setups or tight spaces, while its advanced cooling system ensures optimal performance during intense gaming sessions. With its powerful hardware and attention to detail, the Corsair One i300 is an excellent choice for gamers who demand both power and aesthetics in their gaming rig.",
    },
    {
        name: 'CyberPowerPC Gamer Master',
        slug: 'CyberPowerPC-Gamer-Master',
        category: 'desktops',
        image: '/images/desktop8.png',
        price: 900,
        brand: 'CyberPowerPC',
        rating: 4.3,
        numReviews: 12,
        countInStock: 20,
        description: "The CyberPowerPC Gamer Master is a high-performance gaming PC designed for immersive gaming experiences. Equipped with powerful hardware, including a robust processor and advanced graphics card, it effortlessly handles demanding games with ease. The sleek design and customizable RGB lighting add a touch of style to any gaming setup. Whether you're a casual gamer or a dedicated enthusiast, the CyberPowerPC Gamer Master is built to deliver exceptional gaming performance and take your gameplay to the next level.",
    },
    {
        name: 'CyberPowerPC Gamer Supreme',
        slug: 'CyberPowerPC-Gamer-Supreme',
        category: 'desktops',
        image: '/images/desktop9.png',
        price: 1800,
        brand: 'CyberPowerPC',
        rating: 5.0,
        numReviews: 8,
        countInStock: 20,
        description: "The CyberPowerPC Gamer Supreme is a top-of-the-line gaming PC that pushes the boundaries of performance. With its powerful hardware configuration, including a high-end processor and cutting-edge graphics card, it delivers unrivaled speed and graphics capabilities for an immersive gaming experience. The sleek and modern design of the Gamer Supreme, combined with customizable RGB lighting, adds a touch of sophistication to any gaming setup. Whether you're a competitive gamer or a content creator, the CyberPowerPC Gamer Supreme is built to handle the most demanding games and applications, making it the ultimate choice for enthusiasts seeking top-tier performance.",
    },
]

export default desktopsList;