const laptopsList = [
    {
        name: 'Gigabyte Aorus 17',
        slug: 'Gigabyte-Aorus-17',
        category: 'laptops',
        image: '/images/laptop1.png',
        price: 2500,
        brand: 'Gigabyte',
        rating: 5.0,
        numReviews: 17,
        countInStock: 20,
        description: "The Gigabyte Aorus 17 gaming laptop is a powerful and feature-packed device designed to deliver an exceptional gaming experience. With its high-performance hardware, including top-tier processors and graphics cards, it ensures smooth gameplay and stunning visuals. The laptop boasts a large, high-resolution display, offering immersive gaming and vibrant colors. Its advanced cooling system helps to keep temperatures under control during intense gaming sessions. Additionally, the Aorus 17 is equipped with a range of customizable RGB lighting options, enhancing its aesthetic appeal. Overall, the Aorus 17 is a top choice for gamers seeking top-notch performance and immersive gaming experience on a portable platform.",
    },
    {
        name: 'Gigabyte G5',
        slug: 'Gigabyte-G5',
        category: 'laptops',
        image: '/images/laptop2.png',
        price: 900,
        brand: 'Gigabyte',
        rating: 4.7,
        numReviews: 14,
        countInStock: 20,
        description: "The Gigabyte G5 is a gaming laptop that packs a punch in terms of performance. With its powerful hardware and dedicated graphics card, it delivers smooth gaming and impressive visuals. The laptop features a vibrant display, providing an immersive gaming experience. It also boasts an efficient cooling system to maintain optimal temperatures during extended gaming sessions. With its sleek design and customizable features, the Gigabyte G5 offers both style and substance for gamers looking for an enjoyable gaming experience.",
    },
    {
        name: 'Lenovo Legion Pro 7i',
        slug: 'Lenovo-Legion-Pro-7i',
        category: 'laptops',
        image: '/images/laptop3.png',
        price: 2000,
        brand: 'Lenovo',
        rating: 5.0,
        numReviews: 8,
        countInStock: 20,
        description: "The Lenovo Legion Pro 7i is a high-performance gaming laptop designed to deliver an exceptional gaming experience. With its powerful hardware, including top-tier processors and graphics cards, it ensures smooth gameplay and impressive visuals. The laptop features a vibrant and immersive display, offering stunning visuals for gaming and multimedia. Its advanced cooling system helps to prevent overheating during intense gaming sessions. With its sleek design and customizable RGB lighting, the Legion Pro 7i is a stylish choice for gamers seeking top-notch performance and immersive gameplay.",
    },
    {
        name: 'MSI Raider GE76',
        slug: 'MSI-Raider-GE76',
        category: 'laptops',
        image: '/images/laptop4.png',
        price: 4000,
        brand: 'MSI',
        rating: 5.0,
        numReviews: 2,
        countInStock: 20,
        description: "The MSI Raider GE76 is a powerful gaming laptop that delivers exceptional performance. With its high-performance hardware and top-tier graphics card, it provides smooth gameplay and impressive visuals. The laptop features a large, high-resolution display, offering an immersive gaming experience. Its advanced cooling system helps maintain optimal temperatures during intense gaming sessions. With its sleek design and customizable RGB lighting, the Raider GE76 combines power and style for gamers seeking an immersive gaming experience on the go.",
    },
    {
        name: 'Razer Blade 15',
        slug: 'Razer-Blade-15',
        category: 'laptops',
        image: '/images/laptop5.png',
        price: 2800,
        brand: 'Razer',
        rating: 5.0,
        numReviews: 6,
        countInStock: 20,
        description: "The Razer Blade 15 is a premium gaming laptop that combines power and portability. With its high-performance hardware and dedicated graphics card, it delivers smooth gameplay and stunning visuals. The laptop features a sleek design and a thin bezel display, providing an immersive gaming experience. Its advanced cooling system ensures efficient heat dissipation during intense gaming sessions. The Razer Blade 15 is a stylish choice for gamers seeking top-tier performance in a compact and visually appealing package.",
    },
    {
        name: 'Razer Blade 18',
        slug: 'Razer-Blade-18',
        category: 'laptops',
        image: '/images/laptop6.png',
        price: 3000,
        brand: 'Razer',
        rating: 5.0,
        numReviews: 10,
        countInStock: 20,
        description: "The Razer Blade 18 is an impressive gaming laptop with high-performance capabilities. It boasts a sleek design and a large high-resolution display, offering stunning visuals. The laptop incorporates advanced cooling technology to ensure optimal performance during intense gaming sessions. With customizable RGB lighting, the Razer Blade 18 adds a touch of personalization to the gaming experience. Overall, it is a top choice for gamers looking for power, style, and immersive gameplay in a portable package.",
    },
    {
        name: 'Asus ROG Strix Scar 17',
        slug: 'Asus-ROG-Strix-Scar-17',
        category: 'laptops',
        image: '/images/laptop7.png',
        price: 2800,
        brand: 'Asus',
        rating: 4.3,
        numReviews: 17,
        countInStock: 20,
        description: "The Asus ROG Strix Scar 17 is a high-performance gaming laptop designed to elevate your gaming experience. With its powerful hardware and dedicated graphics card, it delivers smooth gameplay and exceptional visuals. The laptop features a large, high-refresh-rate display, offering immersive and fluid gaming visuals. Its advanced cooling system ensures efficient heat dissipation, allowing for prolonged gaming sessions without overheating. With its bold design and customizable RGB lighting, the ROG Strix Scar 17 stands out as a stylish choice for gamers seeking top-tier performance and an immersive gaming experience.",
    },
    {
        name: 'Asus ROG Zephyrus G14',
        slug: 'Asus-ROG-Zephyrus-G14',
        category: 'laptops',
        image: '/images/laptop8.png',
        price: 1800,
        brand: 'Asus',
        rating: 4.7,
        numReviews: 23,
        countInStock: 20,
        description: "The Asus ROG Zephyrus G14 is a compact and powerful gaming laptop that redefines portable gaming. With its high-performance hardware and dedicated graphics card, it delivers smooth gameplay and impressive visuals. The laptop features a stunning 14-inch display with a high refresh rate, offering immersive and vibrant gaming experiences. Its innovative cooling system ensures optimal performance during intense gaming sessions. With its sleek and lightweight design, the Zephyrus G14 is a perfect choice for gamers on the go, combining portability and power for an unmatched gaming experience.",
    },
    {
        name: 'Asus ROG Zephyrus M16',
        slug: 'Asus-ROG-Zephyrus-M16',
        category: 'laptops',
        image: '/images/laptop9.png',
        price: 2500,
        brand: 'Asus',
        rating: 4.8,
        numReviews: 9,
        countInStock: 20,
        description: "The Asus ROG Zephyrus M16 is a cutting-edge gaming laptop that offers an exceptional gaming experience. With its powerful hardware and dedicated graphics card, it delivers smooth gameplay and stunning visuals. The laptop features a vibrant and immersive display with a high refresh rate, providing fluid and lifelike visuals. Its advanced cooling system ensures optimal performance even during intense gaming sessions. With its sleek and slim design, the Zephyrus M16 is a stylish and portable choice for gamers who prioritize both power and aesthetics.",
    },
]

export default laptopsList;